language: objective-c
osx_image: xcode7.1
env:
  global:
    - LC_CTYPE=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild test -scheme EitherSwift -sdk iphonesimulator | xcpretty -c
notifications:
  email: false
